### PR TITLE
Changed leave message from the users id to the users username.

### PR DESCRIPTION
**Pull request by cal3432**
Also implemented the random leave messages 👍 

before you say "oh but you can do member.user to get the user :P" this wont work as you cannot get the user class of a user that has left the server. discord.js only keeps the member object, the user object is kept in v12+

### CODE REVIEW

**Comment by HarmoGlace** [comment]
No, it is useless... You can just use `member.user.fetch()`, it is not needed to create yourself a cache, d.js already has a cache...

**Comment by HarmoGlace** [comment]
Btw don't use var

**Comment by cal3432** [comment]
This is running on v11 not v12, v11 does not cached member leaves

**Comment by cal3432** [comment]
image

**Comment by HarmoGlace** [comment]
As I said, if it is not cached then fetch it but do not create yourself a cache....

**Pull request closed without merging**
